version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david
      POSTGRES_DB: cvAngular
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
