version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: david
      POSTGRES_DB: cvAngular
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data:
